# Generated by Django 5.2.1 on 2025-11-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='end_time',
        ),
    ]
