# Generated by Django 5.2.1 on 2025-11-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_conference_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.TextField(help_text="Comma-separated list of participants (e.g., 'Xã A, Xã B')")),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_locations', to='schedule.conference')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.location')),
            ],
            options={
                'unique_together': {('conference', 'location')},
            },
        ),
    ]
