# Generated by Django 5.2.1 on 2025-11-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_participant_delete_conferencelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='schedule.location'),
        ),
    ]
