# Generated by Django 5.2.1 on 2025-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_participant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='format',
            field=models.CharField(choices=[('bca', 'Từ Bộ Công an'), ('xuong_co_so', 'Xuống cơ sở'), ('tinh_uy', 'Từ Tỉnh ủy')], default='bca', max_length=20),
        ),
    ]
